### PR TITLE
Bug fixes #1162  download_sensor.py add error if auth fails

### LINKED ISSUE #1162: download_sensor.py / no error message when authentification failed
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.
```
$ python3 download_sensor.py  -k $KEY -s $BAD_PASS -o centos

No results, check your filter and try your query again.
```

When debugging, i see that the sensors results contains:
```
{
  'status_code': 401,
  'headers': {},
  'body': {
    'errors': [
       {
           'message': 'Failed to issue token.'
       }
    ],
    'resources': []
  }
}
```
**Expected behavior**

a message saying that authentification has failed

**Environment (please complete the following information):**
 - OS: RedHat 9
 - Python: 3.9
 - FalconPy: 1.4.3

**Additional context**

### PR DESCRIPTION
**Pull request by nesies**
Fixes #1162

### CODE REVIEW

**Comment by jshcodes** [comment]
Unit test failures are as expected.

Pylint issues appear to be related to differences in the 3.2.2 version.  Reviewing now.

**Comment by nesies** [comment]
my PR  created so much CI errors ?

**Comment by jshcodes** [comment]
> my PR created so much CI errors ?

Only due to missing security keys used for unit testing. This is a known issue, your submission is fine and will merge this week. (Thank you for your contribution!!) 😄

**Review by jshcodes — APPROVED** [review]
Made a minor change to adjust the error messaging and add a SystemExit.

Local unit testing passes for this submission.

Thank you for your contribution! 🙇

**Pull request merged**
