### PR TITLE
Setup GitBooks integration

### PR DESCRIPTION
**Pull request by shawndwells**
This PR sets up scaffolding behind https://crowdstrike.gitbook.io/falconpy/

Once merged I'll update the gitbook backend to point to this repo.

One choice that needs to be made is if the docs should live in their own branch, or a directory off main. Pushing between branches is slightly annoying and might push away would-be fly-by committers, so this PR initially uses a ``docs`` folder in main. What does everyone think?

### CODE REVIEW

**Comment by jshcodes** [comment]
1. I'm completely onboard with this, out of the gate the functionality is better.
2. I like the idea of keeping the wiki content in ```docs```.  Originally this was my intent.
3. Since I'm generating a lot of the documentation from the swagger, we could also consider a ```util``` folder to hold my generator. (And perhaps the Uber class API endpoint list generator and my local run-tests pytest script?) I'll also need to tweak it a bit to match any formatting requirements for the new site's version of markdown. (Not a big deal.)

**Comment by shawndwells** [comment]
> 1. I'm completely onboard with this, out of the gate the functionality is better.

👍 

> 2. I like the idea of keeping the wiki content in `docs`.  Originally this was my intent.

Agreed. Makes the structure simpler.

> 3. Since I'm generating a lot of the documentation from the swagger, we could also consider a `util` folder to hold my generator. (And perhaps the Uber class API endpoint list generator and my local run-tests pytest script?) I'll also need to tweak it a bit to match any formatting requirements for the new site's version of markdown. (Not a big deal.)

By all means. Some of the wiki pages have some style errors (eg code blocks not extending all the way). Figured we could sort that out after merge.

**Comment by shawndwells** [comment]
@jshcodes if/when you review & merge, I'll update the backend of GitBooks. Right now it points to my dev branch.

Also - see https://www.falconpy.io/

**Review by jshcodes — APPROVED** [review]

**Comment by shawndwells** [comment]
@jshcodes We're live at https://falconpy.io!

**Pull request merged**
