### PR TITLE
Pin a specific version of setuptools to prevent issues with the new release

### PR DESCRIPTION
**Pull request by gansel51**
# Pin a specific version of setuptools to prevent issues with the new release

We have had issues with using setuptools versions >70.3.0. Whenever we utilize those versions, we've noticed Azure driver failures on Databricks. Pinning this version of setuptools successfully corrected the issue, and prevents future failures by placing an upper bound on the version of setuptools being installed.

- [x] Bug fixes 

#### Unit test coverage
```shell
NOT REQUIRED FOR DEPENDENCY UPDATES
```

#### Bandit analysis
```shell
NOT REQUIRED FOR DEPENDENCY UPDATES
```

## Issues resolved
+ Bug fix: Pins the version of __setuptools__ to `v70.3.0`. This prevents a bug with Microsoft Azure driver failures coming from a yanked release of __setuptools__ (`v71.0.1`).
    - `requirements-dev.txt`
    - `requirements.txt`

### CODE REVIEW

**Comment by gansel51** [comment]
I don't have a Falcon API key so I'm unable to finish running the tests!

**Comment by jshcodes** [comment]
> I don't have a Falcon API key so I'm unable to finish running the tests!

No worries, we'll get this merged. Thank you for your contribution!!

**Comment by gansel51** [comment]
> > I don't have a Falcon API key so I'm unable to finish running the tests!
> 
> No worries, we'll get this merged. Thank you for your contribution!!

thanks @jshcodes!

**Review by abaiju15 — APPROVED** [review]
Thank you @gansel51!! Nicely done! 🚀🚀🚀

**Comment by jshcodes** [comment]
Merging this to the `dev` branch so we can do additional testing.

**Review by jshcodes — APPROVED** [review]
Thank you for your contribution!

**Comment by pranavrajtyagi-ab** [comment]
thanks @gansel51  and @jshcodes

**Pull request merged**
